listener {
	timeout = 600
    on-timeout = bash -c "pidof hyprlock || (grim ~/.config/hypr/current-screen.png && hyprlock)"
    # on-timeout = bash -c "pkill hyprlock; grim ~/.config/hypr/current-screen.png; hyprlock"
	# on-timeout = bash -c "pkill swaylock; ~/.config/sway/lock.sh"
}

listener {
	timeout = 600
	on-timeout = nu -c 'hyprctl clients -j | from json | where {|i| $i.class == "Logseq"} | if ($in | length) >= 1 {hyprctl dispatch $"hl.dsp.focus\({ window = \"address:($in.0.address)\"}\)"}'
}

listener {
	timeout = 900
	on-timeout = hyprctl dispatch "hl.dsp.dpms({ action = \"off\" })"
	on-resume = hyprctl dispatch "hl.dsp.dpms({ action = \"on\" })"
}

# listener {
# 	timeout = 3600
# 	on-timeout = systemctl suspend
# }
