theme = "tokyonight_storm"

[editor]
idle-timeout = 800
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.file-picker]
hidden = false

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 0
focus-lost = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[keys.insert]
"C-h" = "move_char_left"
"C-l" = "move_char_right"
"C-j" = "move_visual_line_down"
"C-k" = "move_visual_line_up"
left = "no_op"
right = "no_op"
up = "no_op"
down = "no_op"

[keys.normal]
left = "no_op"
right = "no_op"
up = "no_op"
down = "no_op"

C-h = "@b"
C-l = "@w"
C-j = "move_line_down"
C-k = "move_line_up"
C-J = "move_line_down"
C-K = "move_line_up"

"C-H" = "@b"
"C-L" = "@w"
h = "move_char_left"
l = "move_char_right"
j = "move_line_down"
k = "move_line_up"
