theme = "tokyonight_storm"

[editor]
shell = ["nu", "-c"]
idle-timeout = 800
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.file-picker]
hidden = false

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 0
focus-lost = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[keys.insert]
# "esc" = [
#   ":sh echo $(fcitx5-remote -n) > /tmp/fcitx5state; fcitx5-remote -c",
#   "normal_mode",
# ]
"C-h" = "move_char_left"
"C-l" = "move_char_right"
"C-j" = "move_visual_line_down"
"C-k" = "move_visual_line_up"
left = "no_op"
right = "no_op"
up = "no_op"
down = "no_op"

[keys.normal]
# i = [
#   ":sh if [ -e \"/tmp/fcitx5state\" ] && [ $(cat /tmp/fcitx5state) = \"anthy\" ]; then fcitx5-remote -o; fi",
#   "insert_mode",
# ]
# a = [
#   ":sh if [ -e \"/tmp/fcitx5state\" ] && [ $(cat /tmp/fcitx5state) = \"anthy\" ]; then fcitx5-remote -o; fi",
#   "append_mode",
# ]
# c = [
#   ":sh if [ -e \"/tmp/fcitx5state\" ] && [ $(cat /tmp/fcitx5state) = \"anthy\" ]; then fcitx5-remote -o; fi",
#   "change_selection",
# ]
# o = [
#   ":sh if [ -e \"/tmp/fcitx5state\" ] && [ $(cat /tmp/fcitx5state) = \"anthy\" ]; then fcitx5-remote -o; fi",
#   "open_below",
# ]
# O = [
#   ":sh if [ -e \"/tmp/fcitx5state\" ] && [ $(cat /tmp/fcitx5state) = \"anthy\" ]; then fcitx5-remote -o; fi",
#   "open_above",
# ]

left = "no_op"
right = "no_op"
up = "no_op"
down = "no_op"

# C-h = "@b"
# C-l = "@w"
# C-j = "move_line_down"
# C-k = "move_line_up"
# C-J = "move_line_down"
# C-K = "move_line_up"

# "C-H" = "@b"
# "C-L" = "@w"
h = "move_char_left"
l = "move_char_right"
j = "move_line_down"
k = "move_line_up"
