[language-server.tailwindcss]
command = "tailwindcss-language-server"
config = { userLanguages = { rust = "html", "*.rs" = "html" } }
args = ["--stdio"]

[language-server.asm-lsp]
command = "asm-lsp"

[[language]]
name = "nasm"
scope = "source.asm"
file-types = ["asm"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss"]
auto-format = false

[language-server.rust-analyzer]
config = { cargo = { allFeatures = true } }

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["--write"] }

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = ["sql-language-server"]

[[language]]
name = "dart"
auto-format = false

[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false

[[language]]
name = "vue"
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server", "tailwindcss"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/home/marfa/.npm-global/lib/node_modules/@vue/language-server/"
languages = ["vue"]

[[language]]
name = "toml"
auto-format = false
formatter = { command = "taplo", args = ["fmt", "-"] }
