[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.asm-lsp]
command = "asm-lsp"

[[language]]
name = "nasm"
scope = "source.asm"
file-types = ["asm"]
# language-servers = ["asm-lsp"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss"]
auto-format = false

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["--write"] }

[[language]]
name = "dart"
auto-format = false

[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false

[[language]]
name = "toml"
auto-format = false
formatter = { command = "taplo", args = ["fmt", "-"] }
