[window]
opacity = 0.7

[font]
normal = { family = "JetBrainsMonoNLNerdFont", style = "Regular" }
bold = { family = "JetBrainsMonoNLNerdFont", style = "Bold" }
italic = { family = "JetBrainsMonoNLNerdFont", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNLNerdFont", style = "Bold Italic" }

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#f7f7f7"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#f7f7f7"
yellow = "#e0af68"

[colors.primary]
background = "#24283b"
foreground = "#f7f7f7"
